name: "[Add Icons]: "
description: "Template for adding new icons"
title: "[Add Icons]: "
labels:
  - enhancement
body: |
  Please check the following before submitting your PR:

  - [ ] Added to 'lib/iconsData.ts'
  - [ ] Tested the Icons

inputs:
  icons_added:
    type: textarea
    description: "Enter the names of the icons you added, separated by commas or new lines."
    required: true
    default: ""
